spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_mitradayakreasi
    username: postgres
    password: admin 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB